var hierarchy =
[
    [ "CustomTypeFactories", null, [
      [ "ml::AlwaysFailingTypeFactories", "classml_1_1AlwaysFailingTypeFactories.html", null ],
      [ "ml::TreeTypeFactories", "classml_1_1TreeTypeFactories.html", null ]
    ] ],
    [ "Forest", "classForest.html", null ],
    [ "ForestPrediction", "classForestPrediction.html", null ],
    [ "NNBuilder", "classNNBuilder.html", null ],
    [ "ml::Node", "structml_1_1Node.html", null ],
    [ "OpaqueType", null, [
      [ "ml::TreeType", "classml_1_1TreeType.html", null ]
    ] ],
    [ "ml::Tree", "classml_1_1Tree.html", null ],
    [ "ml::TreeT", "structml_1_1TreeT.html", null ],
    [ "exec::VectorFunction", null, [
      [ "MLFunction", "classMLFunction.html", [
        [ "Argmax", "classArgmax.html", null ],
        [ "BatchNorm1D", "classBatchNorm1D.html", null ],
        [ "ChangeRating", "classChangeRating.html", null ],
        [ "ChatGPT", "classChatGPT.html", null ],
        [ "ChatGPTRecommender", "classChatGPTRecommender.html", null ],
        [ "Concat", "classConcat.html", null ],
        [ "ConvertDoubleArrayToFloatArray", "classConvertDoubleArrayToFloatArray.html", null ],
        [ "ConvertDoubleToFloatArray", "classConvertDoubleToFloatArray.html", null ],
        [ "ConvertToFloatArray", "classConvertToFloatArray.html", null ],
        [ "ConvertToIntArray", "classConvertToIntArray.html", null ],
        [ "Convolute", "classConvolute.html", null ],
        [ "CosineSimilarity", "classCosineSimilarity.html", null ],
        [ "DateToTimestamp", "classDateToTimestamp.html", null ],
        [ "DotProduct", "classDotProduct.html", null ],
        [ "Dropout", "classDropout.html", null ],
        [ "Embedding", "classEmbedding.html", null ],
        [ "FullyConnectWithBatchNormAndRelu", "classFullyConnectWithBatchNormAndRelu.html", null ],
        [ "GetAge", "classGetAge.html", null ],
        [ "GetBinaryClass", "classGetBinaryClass.html", null ],
        [ "GetCustomerFeatures", "classGetCustomerFeatures.html", null ],
        [ "GetTransactionFeatures", "classGetTransactionFeatures.html", null ],
        [ "HuggingFaceServerless", "classHuggingFaceServerless.html", null ],
        [ "HuggingFaceTokenizer", "classHuggingFaceTokenizer.html", null ],
        [ "IntEncoder", "classIntEncoder.html", null ],
        [ "IsWeekday", "classIsWeekday.html", null ],
        [ "MatrixAddition", "classMatrixAddition.html", null ],
        [ "MatrixMultiply", "classMatrixMultiply.html", null ],
        [ "MatrixMultiply_Block", "classMatrixMultiply__Block.html", null ],
        [ "MatrixMultiply_b", "classMatrixMultiply__b.html", null ],
        [ "MatrixMultiply_h", "classMatrixMultiply__h.html", null ],
        [ "MatrixVectorAddition", "classMatrixVectorAddition.html", null ],
        [ "MaxPool", "classMaxPool.html", null ],
        [ "MinMaxScaler", "classMinMaxScaler.html", null ],
        [ "MultiHotNormalizedEncoder", "classMultiHotNormalizedEncoder.html", null ],
        [ "PositionEncoding", "classPositionEncoding.html", null ],
        [ "RAG", "classRAG.html", null ],
        [ "Relu", "classRelu.html", null ],
        [ "SVD", "classSVD.html", null ],
        [ "SequencePooling", "classSequencePooling.html", null ],
        [ "Sigmoid", "classSigmoid.html", null ],
        [ "Softmax", "classSoftmax.html", null ],
        [ "StringEncoder", "classStringEncoder.html", null ],
        [ "StringVariadicEncoder", "classStringVariadicEncoder.html", null ],
        [ "TimeDiffInDays", "classTimeDiffInDays.html", null ],
        [ "TorchCNN", "classTorchCNN.html", null ],
        [ "TorchConvolute", "classTorchConvolute.html", null ],
        [ "TorchDNN", "classTorchDNN.html", null ],
        [ "TorchDNN2Level", "classTorchDNN2Level.html", null ],
        [ "TorchDNNKernel", "classTorchDNNKernel.html", null ],
        [ "TorchDNNV2", "classTorchDNNV2.html", null ],
        [ "TorchDNNV2CUDA", "classTorchDNNV2CUDA.html", null ],
        [ "TorchDNN_Multi", "classTorchDNN__Multi.html", null ],
        [ "VectorScalarAddition", "classVectorScalarAddition.html", null ],
        [ "ml::TreePrediction", "classml_1_1TreePrediction.html", null ],
        [ "ml::VeloxTreePrediction", "classml_1_1VeloxTreePrediction.html", null ],
        [ "ml::XGBoostPrediction", "classml_1_1XGBoostPrediction.html", null ]
      ] ],
      [ "ml::VeloxTreeConstruction", "classml_1_1VeloxTreeConstruction.html", null ]
    ] ],
    [ "ml::VeloxTreePredictionSimpleFunction< T >", "structml_1_1VeloxTreePredictionSimpleFunction.html", null ],
    [ "ml::XGBoost", "classml_1_1XGBoost.html", null ]
];